image:
  repository: acrgitopsyavuz2026.azurecr.io/my-app
  tag: 2331165ea972d73efc8173c66694a06e0f297f94
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi